# DB 설정; url: 데이터베이스의 경로.
# mysql 사용, 내 컴퓨터(로컬)의 경로, 사용한 데이터베이스 localhost:{포트 번호}/{DB 이름} ('?' 뒤에 붙은 건 설정들)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scott?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  # html 등, 리소스 경로의 파일을 즉시 변경(새로고침)
  devtools:
    restart:
      enabled: true

# http 로그
logging:
  level:
    org.apache.coyote.http11: trace